In [2]:
import sys
import cv2
import imp
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
import os
import MainWindow
imp.reload(MainWindow)
from MainWindow import Ui_MainWindow
import numpy as np
import math
import pdb
envpath = '/home/x/.conda/envs/ML/lib/python3.9/site-packages/cv2/qt/plugins/platforms'
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = envpath

In [3]:
class ACMWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(ACMWindow, self).__init__()
        self.setupUi(self)
        self.selectImageButton.clicked.connect(self.on_click_select_image)
        self.img = None
    
    def on_click_select_image(self):
        image_path = QtWidgets.QFileDialog.getOpenFileName(None, '选取文件', './', "(*.jpeg);;(*.png);;(*.jpg)")
        self.imageTitleLabel.setText(image_path[0])
        self.imageTitleLabel.show()
        
        self.img = cv2.imread(image_path[0])
        cv2.imshow('img',self.img)
        self.Snake()
    
    def Snake(self):
        wl = 1.
        we = 1.
        wt = 1.
        
        Gaussian_kernel_size = (3,3)
        Gaussian_sigma = 0.1
        
        height, width = self.img.shape[0], self.img.shape[1]
        grayImage = cv2.cvtColor(self.img, cv2.COLOR_BGR2GRAY)
        
        # 计算外部力 E_line,E_edge,
        # 计算 E_line，就是经过高斯平滑后的图像
        pdb.set_trace()
        E_line = cv2.GaussianBlur(grayImage, Gaussian_kernel_size, Gaussian_sigma)
        
        # 计算 E_edge 利用Sobel算子来获取图像的梯度
        gradx = cv2.Sobel(grayImage, cv2.CV_16S, 1, 0)
        grady = cv2.Sobel(grayImage, cv2.CV_16S, 0, 1)
        
        E_edge = -np.sqrt(gradx**2 + grady**2)
        
        # 计算 E_term 端点能量，
        m1 = np.array([-1, 1])
        m2 = np.array([[-1], [1]])
        m3 = np.array([1, -2, 1])
        m4 = np.array([[1], [-2], [1]])
        m5 = np.array([[1, -1], [-1, 1]])
        
        cx = cv2.filter2D(grayImage, -1, m1)
        cy = cv2.filter2D(grayImage, -1, m2)
        cxx = cv2.filter2D(grayImage, -1, m3)
        cyy = cv2.filter2D(grayImage, -1, m4)
        cxy = cv2.filter2D(grayImage, -1, m5)
        
        E_term = (cyy * cx**2 - 2 * cxy * cx * cy + cxx * cy**2) / (cx**2 + cy**2)**1.5
        
        # 计算总体的外部能量
        E_ext = (wl*E_line + we*E_edge - wt*E_term)
        
        
if __name__ == '__main__':
    app = QtCore.QCoreApplication.instance()
    if app is None:
        app = QtWidgets.QApplication(sys.argv)
    window = ACMWindow()
    window.show()
    sys.exit(app.exec_())

QObject::moveToThread: Current thread (0x5591908d8680) is not the object's thread (0x5591907e9400).
Cannot move to target thread (0x5591908d8680)

QObject::moveToThread: Current thread (0x5591907e9400) is not the object's thread (0x5591908d8680).
Cannot move to target thread (0x5591907e9400)

QObject::moveToThread: Current thread (0x5591907e9400) is not the object's thread (0x5591908d8680).
Cannot move to target thread (0x5591907e9400)

QObject::moveToThread: Current thread (0x5591907e9400) is not the object's thread (0x5591908d8680).
Cannot move to target thread (0x5591907e9400)

QObject::moveToThread: Current thread (0x5591907e9400) is not the object's thread (0x5591908d8680).
Cannot move to target thread (0x5591907e9400)

QObject::moveToThread: Current thread (0x5591907e9400) is not the object's thread (0x5591908d8680).
Cannot move to target thread (0x5591907e9400)

QObject::moveToThread: Current thread (0x5591907e9400) is not the object's thread (0x5591908d8680).
Cannot move to tar

> /tmp/ipykernel_1928320/3027318843.py(27)Snake()
     25         # 计算 E_line，就是经过高斯平滑后的图像
     26         pdb.set_trace()
---> 27         E_line = cv2.GaussianBlur(grayImage, Gaussian_kernel_size, Gaussian_sigma)
     28 
     29         # 计算 E_edge 利用Sobel算子来获取图像的梯度

ipdb> 
ipdb> 
ipdb> n
> /tmp/ipykernel_1928320/3027318843.py(30)Snake()
     28 
     29         # 计算 E_edge 利用Sobel算子来获取图像的梯度
---> 30         gradx = cv2.Sobel(grayImage, cv2.CV_16S, 1, 0)
     31         grady = cv2.Sobel(grayImage, cv2.CV_16S, 0, 1)
     32 

ipdb> E_line
array([[36, 36, 36, ..., 36, 36, 36],
       [36, 36, 36, ..., 36, 36, 36],
       [36, 36, 36, ..., 36, 36, 36],
       ...,
       [36, 36, 36, ..., 36, 36, 36],
       [36, 36, 36, ..., 36, 36, 36],
       [36, 36, 36, ..., 36, 36, 36]], dtype=uint8)
ipdb> n
> /tmp/ipykernel_1928320/3027318843.py(31)Snake()
     29         # 计算 E_edge 利用Sobel算子来获取图像的梯度
     30         gradx = cv2.Sobel(grayImage, cv2.CV_16S, 1, 0)
---> 31         grady = cv2.Sobel

TypeError: only size-1 arrays can be converted to Python scalars

> /tmp/ipykernel_1928320/3027318843.py(27)Snake()
     25         # 计算 E_line，就是经过高斯平滑后的图像
     26         pdb.set_trace()
---> 27         E_line = cv2.GaussianBlur(grayImage, Gaussian_kernel_size, Gaussian_sigma)
     28 
     29         # 计算 E_edge 利用Sobel算子来获取图像的梯度

ipdb> n
> /tmp/ipykernel_1928320/3027318843.py(30)Snake()
     28 
     29         # 计算 E_edge 利用Sobel算子来获取图像的梯度
---> 30         gradx = cv2.Sobel(grayImage, cv2.CV_16S, 1, 0)
     31         grady = cv2.Sobel(grayImage, cv2.CV_16S, 0, 1)
     32 

ipdb> E_line
array([[53, 42, 42, ..., 22, 22, 33],
       [39, 28, 28, ..., 11, 11, 22],
       [47, 35, 35, ..., 10, 10, 22],
       ...,
       [15,  8,  4, ...,  2,  4, 14],
       [10,  3,  1, ...,  4,  6, 16],
       [28, 21, 18, ..., 16, 18, 27]], dtype=uint8)
ipdb> n
> /tmp/ipykernel_1928320/3027318843.py(31)Snake()
     29         # 计算 E_edge 利用Sobel算子来获取图像的梯度
     30         gradx = cv2.Sobel(grayImage, cv2.CV_16S, 1, 0)
---> 31         grady = cv2.Sobel(grayImage, cv

<stdin>:1: RuntimeWarning: invalid value encountered in sqrt


array([[ 0.       , 44.       , 20.       , ..., 22.       , 44.       ,
         0.       ],
       [26.       , 52.478565 , 34.4093   , ..., 53.310413 , 65.06919  ,
        46.       ],
       [26.       , 53.235325 , 29.832869 , ..., 28.284271 , 51.47815  ,
        22.       ],
       ...,
       [14.       , 44.38468  ,  7.2111025, ..., 13.038404 , 48.6621   ,
         8.       ],
       [52.       , 65.802734 , 56.       , ..., 57.706154 , 72.34639  ,
        54.       ],
       [ 0.       , 38.       ,  2.       , ...,  8.       , 46.       ,
         0.       ]], dtype=float32)
ipdb> c


TypeError: only size-1 arrays can be converted to Python scalars

SystemExit: 0

/home/x/.conda/envs/ML/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3465: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
